export const checkBoxData = [
    { label: "School in vicinity", value: "school_in_vicinity", isChecked: false },
    { label: "Near City Center", value: "near_city_center", isChecked: false },
    { label: "Adjoining Metro Station", value: "adjoining_metro_station", isChecked: false },
    { label: "Peaceful vicinity", value: "peaceful_vicinity", isChecked: false },
    { label: "Safe & Secure Locality", value: "safe_secure_locality", isChecked: false },
    { label: "Desperate Sale", value: "desperate_sale", isChecked: false },
    { label: "Investment Opportunity", value: "investment_opportunity", isChecked: false },
    { label: "Reputed Builder", value: "reputed_builder", isChecked: false },
    { label: "Vastu Compliant", value: "vastu_compliant", isChecked: false },
    { label: "Free Hold", value: "free_hold", isChecked: false },
    { label: "Prime Location", value: "prime_location", isChecked: false },
    { label: "Plenty of Sunlight", value: "plenty_of_sunlight", isChecked: false },
    { label: "High Rental Yield", value: "high_rental_yield", isChecked: false },
    { label: "Affordable", value: "affordable", isChecked: false },
    { label: "Well Ventilated", value: "well_ventilated", isChecked: false },
    { label: "Fully Renovated", value: "fully_renovated", isChecked: false },
    { label: "Ample Parking", value: "ample_parking", isChecked: false },
    { label: "Tasteful Interior", value: "tasteful_interior", isChecked: false },
    { label: "Spacious", value: "spacious", isChecked: false },
    { label: "Gated Society", value: "gated_society", isChecked: false },
    { label: "Luxury Lifestyle", value: "luxury_lifestyle", isChecked: false },
    { label: "Newly Built", value: "newly_built", isChecked: false },
    { label: "Well Maintained", value: "well_maintained", isChecked: false },
    { label: "Family", value: "family", isChecked: false },
    { label: "Quick Deal", value: "quick_deal", isChecked: false },
    { label: "Bachelors", value: "bachelors", isChecked: false },
    { label: "Females Only", value: "females_only", isChecked: false },
];
